import { useState, useRef, useEffect } from "react";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.REACT_APP_SUPABASE_URL,
  process.env.REACT_APP_SUPABASE_ANON_KEY
);

const ANTHROPIC_KEY = process.env.REACT_APP_ANTHROPIC_KEY;

const TEAL = "#1AAFBF";
const TEAL_LIGHT = "#e6f7f9";
const NAV_BG = "#2c3e50";

const CURRENCIES = ["USD","EUR","GBP","AED","NOK","SGD","AUD"];
const DEPARTMENTS = ["Engineering","Deck","Interior","Provisions","Safety","Maintenance","Other"];
const EQUIPMENT = [
  "","Main Engine (Port)","Main Engine (Starboard)","Generator 1","Generator 2",
  "Gearbox (Port)","Gearbox (Starboard)","Bow Thruster","Stern Thruster",
  "Air Conditioning","Watermaker","Fuel Transfer Pump","Bilge Pump System",
  "Fire Suppression System","Anchor & Windlass","Stabilisers","Life Raft (Port)",
  "Life Raft (Starboard)","Tender","Tender Engine","Navigation System","Radar",
  "Autopilot","Hydraulic System","Fresh Water System","Waste Management System","Other / General",
];

const ST = {
  Pending:  { bg:"#FFF8E1", color:"#E65100", border:"#FFE082" },
  Approved: { bg:"#E8F5E9", color:"#2E7D32", border:"#A5D6A7" },
  Rejected: { bg:"#FFEBEE", color:"#C62828", border:"#EF9A9A" },
};

const USERS = {
  ce:      { pin:"1111", role:"CE",      name:"Chief Engineer" },
  captain: { pin:"2222", role:"Captain", name:"Captain" },
};

const DCOL = [TEAL,"#26A69A","#00838F","#4DB6AC","#80CBC4","#006064","#00ACC1"];
const SCOL = [TEAL,"#00838F","#26A69A","#006064","#4DB6AC"];

const emptyForm   = { supplier:"", invoiceNo:"", invoiceDate:"", dueDate:"", amount:"", currency:"EUR", department:"Engineering", equipment:"", jobRef:"", notes:"", fileName:"", budgetId:"" };
const emptyBudget = { name:"", limit:"", currency:"EUR", startDate:"", endDate:"", recurring:false };
const fmt = function(n){ return parseFloat(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}); };

const SS = {
  btnT:  { padding:"8px 16px", fontSize:14, fontWeight:500, background:TEAL, color:"#fff", border:"1px solid "+TEAL, borderRadius:4, cursor:"pointer" },
  btnO:  { padding:"8px 16px", fontSize:14, fontWeight:500, background:"#fff", color:TEAL, border:"1px solid "+TEAL, borderRadius:4, cursor:"pointer" },
  btnG:  { padding:"8px 16px", fontSize:14, background:"#fff", color:"#555", border:"1px solid #ccc", borderRadius:4, cursor:"pointer" },
  btnTs: { padding:"5px 12px", fontSize:13, fontWeight:500, background:TEAL, color:"#fff", border:"1px solid "+TEAL, borderRadius:4, cursor:"pointer" },
  btnGs: { padding:"5px 12px", fontSize:13, background:"#fff", color:"#555", border:"1px solid #ccc", borderRadius:4, cursor:"pointer" },
  inp:   { width:"100%", padding:"8px 11px", fontSize:14, border:"1px solid #ccc", borderRadius:4, outline:"none", fontFamily:"inherit", boxSizing:"border-box" },
  card:  { background:"#fff", border:"1px solid #dde1e7", borderRadius:6, overflow:"hidden" },
};

function downloadInvoicePDF(inv, budgets) {
  var budget = budgets.find(function(b){ return b.id===inv.budget_id||b.id===inv.budgetId; });
  var html = "<html><head><style>body{font-family:Arial,sans-serif;padding:40px;color:#222;max-width:700px;margin:0 auto;}h1{color:#1AAFBF;font-size:24px;margin:0 0 4px;}.sub{color:#888;font-size:13px;margin:0 0 32px;}table{width:100%;border-collapse:collapse;margin-bottom:24px;}td{padding:10px 12px;border-bottom:1px solid #f0f0f0;font-size:14px;}td:first-child{color:#666;width:180px;font-weight:500;}.badge{display:inline-block;padding:4px 12px;border-radius:4px;font-size:13px;font-weight:600;background:#E8F5E9;color:#2E7D32;}.sage{background:#f7f9fc;border:1px solid #dde1e7;border-radius:6px;padding:16px 20px;margin-top:24px;}.sage h3{margin:0 0 12px;font-size:14px;color:#444;}.footer{margin-top:40px;padding-top:16px;border-top:1px solid #eee;font-size:12px;color:#aaa;text-align:center;}</style></head><body>";
  html += "<h1>Invoice Record</h1><p class='sub'>Generated by Invoice Platform &nbsp;·&nbsp; "+new Date().toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})+"</p>";
  html += "<table>";
  html += "<tr><td>Supplier</td><td><strong>"+(inv.supplier||inv.supplier)+"</strong></td></tr>";
  html += "<tr><td>Invoice number</td><td>"+(inv.invoice_no||inv.invoiceNo)+"</td></tr>";
  html += "<tr><td>Invoice date</td><td>"+(inv.invoice_date||inv.invoiceDate)+"</td></tr>";
  html += "<tr><td>Due date</td><td>"+(inv.due_date||inv.dueDate)+"</td></tr>";
  html += "<tr><td>Amount</td><td><strong>"+(inv.currency)+" "+fmt(inv.amount)+"</strong></td></tr>";
  html += "<tr><td>Department</td><td>"+(inv.department)+"</td></tr>";
  if(inv.equipment) html += "<tr><td>Equipment</td><td>"+inv.equipment+"</td></tr>";
  if(inv.job_ref||inv.jobRef) html += "<tr><td>Job reference</td><td>"+(inv.job_ref||inv.jobRef)+"</td></tr>";
  if(budget) html += "<tr><td>Budget</td><td>"+budget.name+"</td></tr>";
  if(inv.notes) html += "<tr><td>Notes</td><td>"+inv.notes+"</td></tr>";
  html += "<tr><td>Status</td><td><span class='badge'>Approved</span></td></tr>";
  html += "</table>";
  html += "<div class='sage'><h3>Sage import reference</h3><table>";
  html += "<tr><td style='color:#666;width:160px'>Supplier name</td><td>"+(inv.supplier)+"</td></tr>";
  html += "<tr><td style='color:#666'>Invoice ref</td><td>"+(inv.invoice_no||inv.invoiceNo)+"</td></tr>";
  html += "<tr><td style='color:#666'>Invoice date</td><td>"+(inv.invoice_date||inv.invoiceDate)+"</td></tr>";
  html += "<tr><td style='color:#666'>Due date</td><td>"+(inv.due_date||inv.dueDate)+"</td></tr>";
  html += "<tr><td style='color:#666'>Net amount</td><td>"+(inv.currency)+" "+fmt(inv.amount)+"</td></tr>";
  html += "<tr><td style='color:#666'>Nominal code</td><td>"+(inv.department)+"</td></tr>";
  html += "</table></div>";
  html += "<div class='footer'>Invoice Platform &nbsp;·&nbsp; Approved by Captain &nbsp;·&nbsp; "+new Date().toLocaleDateString("en-GB")+"</div>";
  html += "</body></html>";
  var blob = new Blob([html], {type:"text/html"});
  var url  = URL.createObjectURL(blob);
  var a    = document.createElement("a");
  a.href = url;
  a.download = "Invoice-"+(inv.invoice_no||inv.invoiceNo)+"-"+inv.supplier.replace(/\s+/g,"-")+".html";
  a.click();
  URL.revokeObjectURL(url);
}

async function extractInvoiceData(file) {
  var b64 = await new Promise(function(res,rej){var r=new FileReader();r.onload=function(){res(r.result.split(",")[1]);};r.onerror=rej;r.readAsDataURL(file);});
  var body = {model:"claude-sonnet-4-20250514",max_tokens:1000,messages:[{role:"user",content:[
    {type:file.type.startsWith("image/")?"image":"document",source:{type:"base64",media_type:file.type,data:b64}},
    {type:"text",text:"Extract invoice data. Return ONLY JSON: supplier, invoiceNo, invoiceDate (YYYY-MM-DD), dueDate (YYYY-MM-DD or empty), amount (number string), currency (ISO 3-letter), notes (max 100 chars), language. No markdown."}
  ]}]};
  try {
    var res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json","x-api-key":ANTHROPIC_KEY,"anthropic-version":"2023-06-01","anthropic-dangerous-direct-browser-access":"true"},body:JSON.stringify(body)});
    var data=await res.json();
    var text=((data.content&&data.content.find(function(b){return b.type==="text";}))|| {}).text||"{}";
    return JSON.parse(text.replace(/```json|```/g,"").trim());
  } catch(e){ return {}; }
}

function LoginScreen(props) {
  var [selected, setSelected] = useState(null);
  var [pin, setPin]           = useState("");
  var [error, setError]       = useState("");
  var [showPin, setShowPin]   = useState(false);

  function tryLogin() {
    var user = Object.values(USERS).find(function(u){ return u.role.toLowerCase()===selected; });
    if (!user) return;
    if (pin === user.pin) { props.onLogin(user.role, user.name); }
    else { setError("Incorrect PIN. Please try again."); setPin(""); }
  }

  return (
    <div style={{minHeight:"100vh",background:"#f4f6f8",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:24}}>
      <div style={{marginBottom:32,textAlign:"center"}}>
        <p style={{fontSize:28,fontWeight:700,color:TEAL,margin:"0 0 6px"}}>INVOICE PLATFORM</p>
        <p style={{fontSize:14,color:"#888",margin:0}}>Vessel invoice management</p>
      </div>
      {!selected && (
        <div style={{background:"#fff",border:"1px solid #dde1e7",borderRadius:8,padding:"32px 40px",width:"100%",maxWidth:380,textAlign:"center"}}>
          <p style={{fontSize:16,fontWeight:600,color:"#222",margin:"0 0 24px"}}>Who are you?</p>
          <div style={{display:"flex",flexDirection:"column",gap:12}}>
            <button onClick={function(){setSelected("ce");setPin("");setError("");}} style={{padding:"16px 20px",fontSize:15,fontWeight:500,background:"#fff",color:"#222",border:"2px solid #dde1e7",borderRadius:8,cursor:"pointer",display:"flex",alignItems:"center",gap:14,textAlign:"left"}}>
              <span style={{fontSize:28}}>🔧</span>
              <div><p style={{margin:"0 0 2px",fontWeight:600}}>Chief Engineer</p><p style={{margin:0,fontSize:12,color:"#888"}}>Upload &amp; manage invoices</p></div>
            </button>
            <button onClick={function(){setSelected("captain");setPin("");setError("");}} style={{padding:"16px 20px",fontSize:15,fontWeight:500,background:"#fff",color:"#222",border:"2px solid #dde1e7",borderRadius:8,cursor:"pointer",display:"flex",alignItems:"center",gap:14,textAlign:"left"}}>
              <span style={{fontSize:28}}>⚓</span>
              <div><p style={{margin:"0 0 2px",fontWeight:600}}>Captain</p><p style={{margin:0,fontSize:12,color:"#888"}}>Review &amp; approve invoices</p></div>
            </button>
          </div>
        </div>
      )}
      {selected && (
        <div style={{background:"#fff",border:"1px solid #dde1e7",borderRadius:8,padding:"32px 40px",width:"100%",maxWidth:340,textAlign:"center"}}>
          <p style={{fontSize:28,margin:"0 0 8px"}}>{selected==="ce"?"🔧":"⚓"}</p>
          <p style={{fontSize:16,fontWeight:600,color:"#222",margin:"0 0 4px"}}>{selected==="ce"?"Chief Engineer":"Captain"}</p>
          <p style={{fontSize:13,color:"#888",margin:"0 0 24px"}}>Enter your PIN to continue</p>
          <div style={{display:"flex",justifyContent:"center",gap:12,marginBottom:8}}>
            {[0,1,2,3].map(function(i){return <div key={i} style={{width:14,height:14,borderRadius:"50%",background:pin.length>i?TEAL:"#e0e0e0"}}/>;}) }
          </div>
          <div style={{position:"relative",marginBottom:16}}>
            <input type={showPin?"text":"password"} value={pin} maxLength={4} placeholder="Enter 4-digit PIN"
              onChange={function(e){setPin(e.target.value.replace(/\D/g,"").slice(0,4));setError("");}}
              onKeyDown={function(e){if(e.key==="Enter")tryLogin();}}
              autoFocus
              style={Object.assign({},SS.inp,{textAlign:"center",fontSize:20,letterSpacing:8,borderColor:error?"#C62828":"#ccc",paddingRight:40})}/>
            <button onClick={function(){setShowPin(function(v){return !v;});}} style={{position:"absolute",right:10,top:"50%",transform:"translateY(-50%)",background:"none",border:"none",cursor:"pointer",fontSize:16,color:"#aaa"}}>{showPin?"🙈":"👁"}</button>
          </div>
          {error && <p style={{fontSize:13,color:"#C62828",margin:"0 0 12px"}}>{error}</p>}
          <button onClick={tryLogin} style={Object.assign({},SS.btnT,{width:"100%",marginBottom:12})}>Sign in</button>
          <button onClick={function(){setSelected(null);setPin("");setError("");}} style={{background:"none",border:"none",fontSize:13,color:"#888",cursor:"pointer"}}>← Back</button>
          <p style={{fontSize:11,color:"#ccc",margin:"20px 0 0"}}>Demo PINs: CE = 1111 &nbsp;·&nbsp; Captain = 2222</p>
        </div>
      )}
    </div>
  );
}

function Badge(props) {
  var s = ST[props.status];
  return <span style={{display:"inline-flex",alignItems:"center",gap:5,padding:"4px 10px",borderRadius:4,fontSize:13,fontWeight:500,background:s.bg,color:s.color,border:"1px solid "+s.border,whiteSpace:"nowrap"}}>{props.status}</span>;
}

function Lbl(props) {
  return <label style={{display:"block",fontSize:13,fontWeight:500,color:"#444",marginBottom:5}}>{props.children}{props.required&&<span style={{color:"#C62828",marginLeft:2}}>*</span>}</label>;
}

function StatCard(props) {
  var accent = props.accent||TEAL;
  return (
    <div style={{background:"#fff",border:"1px solid #dde1e7",borderRadius:6,padding:"16px 20px",borderTop:"3px solid "+accent}}>
      <p style={{fontSize:13,color:"#666",fontWeight:500,margin:"0 0 8px"}}>{props.label}</p>
      <p style={{fontSize:26,fontWeight:700,color:"#222",lineHeight:1,margin:0}}>{props.value}</p>
      {props.sub&&<p style={{fontSize:12,color:"#888",margin:"4px 0 0"}}>{props.sub}</p>}
    </div>
  );
}

function MiniBar(props) {
  return <div style={{height:6,borderRadius:3,background:"#e8e8e8",overflow:"hidden",marginTop:8}}><div style={{height:"100%",width:Math.min(props.pct,100)+"%",background:props.color,borderRadius:3}}/></div>;
}

function DropZone(props) {
  var [drag,setDrag]=useState(false);
  var ref=useRef();
  function handle(f){if(f&&(f.type==="application/pdf"||f.type.startsWith("image/")))props.onFile(f);}
  return (
    <div onDragOver={function(e){e.preventDefault();setDrag(true);}} onDragLeave={function(){setDrag(false);}} onDrop={function(e){e.preventDefault();setDrag(false);handle(e.dataTransfer.files[0]);}} onClick={function(){if(!props.extracting)ref.current.click();}}
      style={{border:"2px dashed "+(drag?TEAL:"#ccc"),borderRadius:6,padding:"32px 20px",cursor:props.extracting?"default":"pointer",textAlign:"center",background:drag?TEAL_LIGHT:"#fafafa"}}>
      <input ref={ref} type="file" accept=".pdf,image/*" style={{display:"none"}} onChange={function(e){handle(e.target.files[0]);}}/>
      {props.extracting?<div><p style={{fontSize:14,fontWeight:500,color:"#333",margin:"0 0 4px"}}>Extracting...</p><p style={{fontSize:13,color:"#777",margin:0}}>EN / IT / FR</p></div>
      :props.fileName?<div><p style={{fontSize:14,fontWeight:500,color:"#333",margin:"0 0 4px"}}>{"✓ "+props.fileName}</p><p style={{fontSize:13,color:"#777",margin:0}}>Click to replace</p></div>
      :<div><p style={{fontSize:22,margin:"0 0 8px"}}>📄</p><p style={{fontSize:14,fontWeight:500,color:"#444",margin:"0 0 4px"}}>Drop invoice PDF here</p><p style={{fontSize:13,color:"#888",margin:0}}>or click to browse · EN · IT · FR</p></div>}
    </div>
  );
}

function InvoiceTable(props) {
  var invoices=props.invoices,budgets=props.budgets,onStatus=props.onStatus,showActions=props.showActions;
  return (
    <table style={{width:"100%",borderCollapse:"collapse",fontSize:14}}>
      <thead><tr style={{background:"#f7f8fa"}}>
        {["Supplier","Invoice No.","Department","Amount","Status","Actions"].map(function(h){return <th key={h} style={{padding:"11px 16px",textAlign:"left",fontWeight:600,color:"#555",fontSize:13,borderBottom:"2px solid #e0e0e0",whiteSpace:"nowrap"}}>{h}</th>;})}
      </tr></thead>
      <tbody>
        {invoices.length===0&&<tr><td colSpan={6} style={{padding:"2.5rem",textAlign:"center",color:"#999"}}>No invoices found</td></tr>}
        {invoices.map(function(inv,i){
          return(
            <tr key={inv.id} style={{borderBottom:"1px solid #f0f0f0",background:i%2===0?"#fff":"#fafbfc"}}>
              <td style={{padding:"13px 16px",fontWeight:600,color:"#222"}}>{inv.supplier}</td>
              <td style={{padding:"13px 16px",color:"#555"}}>{inv.invoice_no||inv.invoiceNo}</td>
              <td style={{padding:"13px 16px",color:"#555"}}>{inv.department}</td>
              <td style={{padding:"13px 16px",fontWeight:600}}>{inv.currency+" "+fmt(inv.amount)}</td>
              <td style={{padding:"13px 16px"}}><Badge status={inv.status}/></td>
              <td style={{padding:"10px 16px"}}>
                <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>
                  {showActions&&inv.status==="Pending"&&<div style={{display:"flex",gap:6}}>
                    <button style={SS.btnTs} onClick={function(){onStatus(inv.id,"Approved");}}>✓ Approve</button>
                    <button style={Object.assign({},SS.btnGs,{color:"#C62828",borderColor:"#EF9A9A"})} onClick={function(){onStatus(inv.id,"Rejected");}}>✕ Reject</button>
                  </div>}
                  {showActions&&inv.status!=="Pending"&&<button style={SS.btnGs} onClick={function(){onStatus(inv.id,"Pending");}}>↺ Reset</button>}
                  {inv.status==="Approved"&&<button onClick={function(){downloadInvoicePDF(inv,budgets);}} style={Object.assign({},SS.btnGs,{color:"#2E7D32",borderColor:"#A5D6A7",fontSize:12,padding:"4px 10px"})}>⬇ Download for Sage</button>}
                </div>
              </td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
}

function BudgetList(props) {
  var budgets=props.budgets,invoices=props.invoices,onSelect=props.onSelect,onAdd=props.onAdd;
  var [addB,setAddB]=useState(false);
  var [bForm,setBForm]=useState(emptyBudget);
  var [bErr,setBErr]=useState({});
  function bSpend(id){return invoices.filter(function(i){return (i.budget_id||i.budgetId)===id&&i.status!=="Rejected";}).reduce(function(s,i){return s+parseFloat(i.amount||0);},0);}
  function bCount(id){return invoices.filter(function(i){return (i.budget_id||i.budgetId)===id;}).length;}
  async function submit(){
    var e={};
    if(!bForm.name.trim())e.name=true;
    if(!bForm.limit||isNaN(bForm.limit)||parseFloat(bForm.limit)<=0)e.limit=true;
    setBErr(e);if(Object.keys(e).length)return;
    var insert={name:bForm.name,limit_amount:parseFloat(bForm.limit),currency:bForm.currency,start_date:bForm.startDate||null,end_date:bForm.endDate||null,recurring:bForm.recurring};
    var res=await supabase.from("budgets").insert([insert]).select();
    if(res.data&&res.data[0])onAdd(res.data[0]);
    setBForm(emptyBudget);setAddB(false);setBErr({});
  }
  return (
    <div>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}>
        <p style={{fontSize:20,fontWeight:700,color:"#222",margin:0}}>Budgets</p>
        <button style={SS.btnT} onClick={function(){setAddB(function(v){return !v;});}}>+ New budget</button>
      </div>
      {addB&&<div style={Object.assign({},SS.card,{padding:20,marginBottom:16})}>
        <p style={{fontSize:14,fontWeight:600,margin:"0 0 14px"}}>New budget</p>
        <div style={{display:"grid",gridTemplateColumns:"2fr 1fr 1fr",gap:14,marginBottom:14}}>
          <div><Lbl required>Name</Lbl><input value={bForm.name} placeholder="e.g. Summer Season" onChange={function(e){var v=e.target.value;setBForm(function(p){return Object.assign({},p,{name:v});});}} style={Object.assign({},SS.inp,{borderColor:bErr.name?"#C62828":"#ccc"})}/>{bErr.name&&<p style={{fontSize:12,color:"#C62828",margin:"4px 0 0"}}>Required</p>}</div>
          <div><Lbl required>Limit</Lbl><input type="number" min="0" value={bForm.limit} placeholder="0.00" onChange={function(e){var v=e.target.value;setBForm(function(p){return Object.assign({},p,{limit:v});});}} style={Object.assign({},SS.inp,{borderColor:bErr.limit?"#C62828":"#ccc"})}/>{bErr.limit&&<p style={{fontSize:12,color:"#C62828",margin:"4px 0 0"}}>Required</p>}</div>
          <div><Lbl>Currency</Lbl><select value={bForm.currency} onChange={function(e){var v=e.target.value;setBForm(function(p){return Object.assign({},p,{currency:v});});}} style={SS.inp}>{CURRENCIES.map(function(c){return <option key={c}>{c}</option>;})}</select></div>
        </div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:14,marginBottom:14}}>
          <div><Lbl>Start date</Lbl><input type="date" value={bForm.startDate} onChange={function(e){var v=e.target.value;setBForm(function(p){return Object.assign({},p,{startDate:v});});}} style={SS.inp}/></div>
          <div><Lbl>End date</Lbl><input type="date" value={bForm.endDate} onChange={function(e){var v=e.target.value;setBForm(function(p){return Object.assign({},p,{endDate:v});});}} style={SS.inp}/></div>
          <div style={{display:"flex",alignItems:"center",gap:8,paddingTop:22}}>
            <input type="checkbox" id="rec" checked={bForm.recurring} onChange={function(e){var v=e.target.checked;setBForm(function(p){return Object.assign({},p,{recurring:v});});}} style={{width:16,height:16,cursor:"pointer"}}/>
            <label htmlFor="rec" style={{fontSize:13,fontWeight:500,color:"#444",cursor:"pointer"}}>Monthly recurring</label>
          </div>
        </div>
        <div style={{display:"flex",gap:8}}>
          <button style={SS.btnTs} onClick={submit}>Create</button>
          <button style={SS.btnGs} onClick={function(){setAddB(false);setBErr({});setBForm(emptyBudget);}}>Cancel</button>
        </div>
      </div>}
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}>
        {budgets.map(function(b){
          var spend=bSpend(b.id),cnt=bCount(b.id);
          var limit=parseFloat(b.limit_amount||b.limit||0);
          var pct=limit>0?(spend/limit)*100:0;
          var over=pct>=100,warn=pct>=80;
          var barColor=over?"#F44336":warn?"#FF9800":"#4CAF50";
          return(
            <div key={b.id} onClick={function(){onSelect(b.id);}} style={{background:"#fff",border:"1px solid #dde1e7",borderRadius:6,padding:"16px 18px",cursor:"pointer",borderTop:"3px solid "+TEAL}}>
              <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:6}}>
                <div>
                  <p style={{fontSize:15,fontWeight:600,color:"#222",margin:"0 0 6px"}}>{b.name}</p>
                  <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>
                    {b.recurring&&<span style={{fontSize:11,fontWeight:600,padding:"2px 8px",borderRadius:10,background:TEAL_LIGHT,color:TEAL,border:"1px solid "+TEAL}}>Monthly</span>}
                    {b.start_date&&b.end_date&&<span style={{fontSize:11,padding:"2px 8px",borderRadius:10,background:"#f0f4f8",color:"#555",border:"1px solid #dde1e7"}}>{new Date(b.start_date).toLocaleDateString("en-GB",{month:"short",year:"numeric"})}{"–"}{new Date(b.end_date).toLocaleDateString("en-GB",{month:"short",year:"numeric"})}</span>}
                  </div>
                </div>
                <span style={{fontSize:18,color:"#bbb"}}>›</span>
              </div>
              <p style={{fontSize:13,color:"#999",margin:"8px 0 10px"}}>{cnt+" invoice"+(cnt!==1?"s":"")}</p>
              <div style={{display:"flex",justifyContent:"space-between",fontSize:13,marginBottom:2}}>
                <span style={{color:"#777"}}>Spent</span>
                <span style={{fontWeight:600}}>{b.currency+" "+fmt(spend)+" "}<span style={{color:"#bbb",fontWeight:400}}>{"/ "+fmt(limit)}</span></span>
              </div>
              <MiniBar pct={pct} color={barColor}/>
              <p style={{fontSize:12,margin:"6px 0 0",color:over?"#C62828":warn?"#E65100":"#888"}}>
                {over?"Over by "+b.currency+" "+fmt(spend-limit):b.currency+" "+fmt(limit-spend)+" remaining · "+Math.round(pct)+"% used"}
              </p>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function BudgetDetail(props) {
  var budget=props.budget,invoices=props.invoices,budgets=props.budgets,onBack=props.onBack,onStatus=props.onStatus;
  var limit=parseFloat(budget.limit_amount||budget.limit||0);
  var ci=invoices.filter(function(i){return (i.budget_id||i.budgetId)===budget.id;});
  var spend=ci.filter(function(i){return i.status!=="Rejected";}).reduce(function(s,i){return s+parseFloat(i.amount||0);},0);
  var rem=limit-spend;
  var pct=limit>0?Math.round((spend/limit)*100):0;
  var byD=DEPARTMENTS.map(function(d){return {dept:d,total:ci.filter(function(i){return i.department===d&&i.status!=="Rejected";}).reduce(function(s,i){return s+parseFloat(i.amount||0);},0)};}).filter(function(d){return d.total>0;});
  var byS=Array.from(new Set(ci.map(function(i){return i.supplier;}))).map(function(s){return {supplier:s,total:ci.filter(function(i){return i.supplier===s&&i.status!=="Rejected";}).reduce(function(s2,i){return s2+parseFloat(i.amount||0);},0)};});
  var cMax=Math.max.apply(null,byD.map(function(d){return d.total;}).concat(byS.map(function(s){return s.total;})).concat([1]));
  return (
    <div>
      <div style={{display:"flex",alignItems:"center",gap:12,marginBottom:20}}>
        <button style={SS.btnGs} onClick={onBack}>← Budgets</button>
        <div>
          <p style={{fontSize:20,fontWeight:700,color:"#222",margin:"0 0 2px"}}>{budget.name}</p>
          <p style={{fontSize:13,color:"#888",margin:0}}>{"Limit: "+budget.currency+" "+fmt(limit)}</p>
        </div>
      </div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:16,marginBottom:24}}>
        <StatCard label="Total spent"  value={budget.currency+" "+fmt(spend)} accent={TEAL}/>
        <StatCard label="Remaining"    value={budget.currency+" "+fmt(Math.max(0,rem))} accent="#4CAF50"/>
        <StatCard label="Budget used"  value={pct+"%"} sub={ci.length+" invoice"+(ci.length!==1?"s":"")} accent="#FF9800"/>
      </div>
      {byD.length>0&&<div style={Object.assign({},SS.card,{padding:20,marginBottom:16})}>
        <p style={{fontSize:13,fontWeight:600,color:"#555",textTransform:"uppercase",letterSpacing:"0.05em",margin:"0 0 16px"}}>Spend by department</p>
        {byD.sort(function(a,b){return b.total-a.total;}).map(function(d,i){return(
          <div key={d.dept} style={{marginBottom:12}}>
            <div style={{display:"flex",justifyContent:"space-between",fontSize:14,marginBottom:5}}>
              <span style={{display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:2,background:DCOL[i%DCOL.length],display:"inline-block"}}/>{d.dept}</span>
              <span style={{fontWeight:600}}>{budget.currency+" "+fmt(d.total)}</span>
            </div>
            <div style={{height:8,borderRadius:4,background:"#eee",overflow:"hidden"}}><div style={{height:"100%",width:((d.total/cMax)*100)+"%",background:DCOL[i%DCOL.length],borderRadius:4}}/></div>
          </div>
        );})}
      </div>}
      {byS.length>0&&<div style={Object.assign({},SS.card,{padding:20,marginBottom:16})}>
        <p style={{fontSize:13,fontWeight:600,color:"#555",textTransform:"uppercase",letterSpacing:"0.05em",margin:"0 0 16px"}}>Spend by supplier</p>
        {byS.sort(function(a,b){return b.total-a.total;}).map(function(s,i){return(
          <div key={s.supplier} style={{marginBottom:12}}>
            <div style={{display:"flex",justifyContent:"space-between",fontSize:14,marginBottom:5}}>
              <span style={{display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:2,background:SCOL[i%SCOL.length],display:"inline-block"}}/>{s.supplier}</span>
              <span style={{fontWeight:600}}>{budget.currency+" "+fmt(s.total)}</span>
            </div>
            <div style={{height:8,borderRadius:4,background:"#eee",overflow:"hidden"}}><div style={{height:"100%",width:((s.total/cMax)*100)+"%",background:SCOL[i%SCOL.length],borderRadius:4}}/></div>
          </div>
        );})}
      </div>}
      <p style={{fontSize:13,fontWeight:600,color:"#555",textTransform:"uppercase",letterSpacing:"0.05em",margin:"0 0 10px"}}>Invoices</p>
      <div style={SS.card}><InvoiceTable invoices={ci} budgets={budgets} onStatus={onStatus} showActions={false}/></div>
    </div>
  );
}

function BulkUpload(props) {
  var onBack=props.onBack,onSubmit=props.onSubmit;
  var [queue,setQueue]=useState([]);
  var [drag,setDrag]=useState(false);
  var fileRef=useRef();
  var idRef=useRef(1000);
  async function handleFiles(files){
    var arr=Array.from(files).filter(function(f){return f.type==="application/pdf"||f.type.startsWith("image/");});
    if(!arr.length)return;
    var items=arr.map(function(f){return {id:idRef.current++,file:f,fileName:f.name,status:"pending",data:Object.assign({},emptyForm,{fileName:f.name})};});
    setQueue(items);
    for(var i=0;i<items.length;i++){
      (function(item){
        var iid=item.id;
        setQueue(function(q){return q.map(function(x){return x.id===iid?Object.assign({},x,{status:"extracting"}):x;});});
        extractInvoiceData(item.file).then(function(d){
          var autoDue="";
          if(d.invoiceDate){var dt=new Date(d.invoiceDate);dt.setDate(dt.getDate()+30);autoDue=d.dueDate||dt.toISOString().split("T")[0];}
          var nd={supplier:d.supplier||"",invoiceNo:d.invoiceNo||"",invoiceDate:d.invoiceDate||"",dueDate:autoDue,amount:d.amount||"",currency:d.currency&&CURRENCIES.includes(d.currency)?d.currency:"EUR",notes:d.notes||"",department:"Engineering",equipment:"",jobRef:"",budgetId:"",fileName:item.file.name};
          var did=item.id;
          setQueue(function(q){return q.map(function(x){return x.id===did?Object.assign({},x,{status:"done",data:nd}):x;});});
        }).catch(function(){
          var eid=item.id;
          setQueue(function(q){return q.map(function(x){return x.id===eid?Object.assign({},x,{status:"error"}):x;});});
        });
      })(items[i]);
    }
    }
  }
  function updateField(id,field,value){setQueue(function(q){return q.map(function(x){return x.id===id?Object.assign({},x,{data:Object.assign({},x.data,{[field]:value})}):x;});});}
  function removeItem(id){setQueue(function(q){return q.filter(function(x){return x.id!==id;});});}
  var done=queue.filter(function(x){return x.status==="done";});
  var extr=queue.filter(function(x){return x.status==="extracting";}).length;
  var total=queue.length;
  var pct=total>0?Math.round((done.length/total)*100):0;
  var allDone=total>0&&queue.every(function(x){return x.status==="done"||x.status==="error";});
  return (
    <div>
      <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:20}}>
        <button style={SS.btnGs} onClick={onBack}>← Back</button>
        <div><p style={{fontSize:20,fontWeight:700,color:"#222",margin:"0 0 2px"}}>Bulk invoice upload</p><p style={{fontSize:13,color:"#888",margin:0}}>Select multiple PDFs — fields extracted automatically</p></div>
      </div>
      {queue.length===0&&(
        <div onDragOver={function(e){e.preventDefault();setDrag(true);}} onDragLeave={function(){setDrag(false);}} onDrop={function(e){e.preventDefault();setDrag(false);handleFiles(e.dataTransfer.files);}} onClick={function(){fileRef.current.click();}}
          style={{border:"2px dashed "+(drag?TEAL:"#ccc"),borderRadius:8,padding:"48px 20px",textAlign:"center",background:drag?TEAL_LIGHT:"#fafafa",cursor:"pointer"}}>
          <input ref={fileRef} type="file" accept=".pdf,image/*" multiple style={{display:"none"}} onChange={function(e){handleFiles(e.target.files);}}/>
          <p style={{fontSize:32,margin:"0 0 12px"}}>📂</p>
          <p style={{fontSize:16,fontWeight:600,color:"#333",margin:"0 0 6px"}}>Drop invoices here or click to browse</p>
          <p style={{fontSize:13,color:"#888",margin:0}}>Hold Ctrl or Cmd to select multiple files</p>
        </div>
      )}
      {queue.length>0&&(
        <div>
          <div style={Object.assign({},SS.card,{padding:"14px 20px",marginBottom:16,display:"flex",alignItems:"center",gap:16})}>
            <div style={{flex:1}}>
              <div style={{display:"flex",justifyContent:"space-between",fontSize:13,marginBottom:6}}>
                <span style={{color:"#555"}}>{extr>0?"Extracting "+done.length+" of "+total+"...":done.length+" of "+total+" extracted"}</span>
                <span style={{fontWeight:600,color:TEAL}}>{pct+"%"}</span>
              </div>
              <div style={{height:6,borderRadius:3,background:"#e8e8e8",overflow:"hidden"}}><div style={{height:"100%",width:pct+"%",background:TEAL,borderRadius:3,transition:"width .3s"}}/></div>
            </div>
            <button style={SS.btnGs} onClick={function(){setQueue([]);}}>Clear all</button>
          </div>
          <div style={Object.assign({},SS.card,{marginBottom:16})}>
            <table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}>
              <thead><tr style={{background:"#f7f8fa"}}>
                {["File","Supplier","Invoice No.","Date","Amount","Cur.","Status",""].map(function(h){return <th key={h} style={{padding:"10px 12px",textAlign:"left",fontWeight:600,color:"#555",fontSize:12,borderBottom:"2px solid #e0e0e0",whiteSpace:"nowrap"}}>{h}</th>;})}
              </tr></thead>
              <tbody>
                {queue.map(function(item,i){return(
                  <tr key={item.id} style={{borderBottom:"1px solid #f0f0f0",background:i%2===0?"#fff":"#fafbfc"}}>
                    <td style={{padding:"8px 12px",color:"#777",fontSize:12,maxWidth:100,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{item.fileName}</td>
                    <td style={{padding:"6px 8px"}}>{item.status==="done"?<input value={item.data.supplier} onChange={function(e){var v=e.target.value;updateField(item.id,"supplier",v);}} style={Object.assign({},SS.inp,{fontSize:13,padding:"4px 8px"})} placeholder="Supplier"/>:<span style={{color:"#aaa",fontSize:12}}>{item.status==="extracting"?"Extracting...":"Queued"}</span>}</td>
                    <td style={{padding:"6px 8px"}}>{item.status==="done"?<input value={item.data.invoiceNo} onChange={function(e){var v=e.target.value;updateField(item.id,"invoiceNo",v);}} style={Object.assign({},SS.inp,{fontSize:13,padding:"4px 8px"})} placeholder="INV-001"/>:<span style={{color:"#aaa",fontSize:12}}>—</span>}</td>
                    <td style={{padding:"6px 8px"}}>{item.status==="done"?<input type="date" value={item.data.invoiceDate} onChange={function(e){var d=e.target.value;var due="";if(d){var dt=new Date(d);dt.setDate(dt.getDate()+30);due=dt.toISOString().split("T")[0];}updateField(item.id,"invoiceDate",d);updateField(item.id,"dueDate",due);}} style={Object.assign({},SS.inp,{fontSize:13,padding:"4px 8px"})}/>:<span style={{color:"#aaa",fontSize:12}}>—</span>}</td>
                    <td style={{padding:"6px 8px"}}>{item.status==="done"?<input type="number" value={item.data.amount} onChange={function(e){var v=e.target.value;updateField(item.id,"amount",v);}} style={Object.assign({},SS.inp,{fontSize:13,padding:"4px 8px",width:80})} placeholder="0.00"/>:<span style={{color:"#aaa",fontSize:12}}>—</span>}</td>
                    <td style={{padding:"6px 8px"}}>{item.status==="done"?<select value={item.data.currency} onChange={function(e){var v=e.target.value;updateField(item.id,"currency",v);}} style={Object.assign({},SS.inp,{fontSize:13,padding:"4px 6px",width:72})}>{CURRENCIES.map(function(c){return <option key={c}>{c}</option>;})}</select>:<span style={{color:"#aaa",fontSize:12}}>—</span>}</td>
                    <td style={{padding:"10px 12px",whiteSpace:"nowrap"}}>
                      {item.status==="extracting"&&<span style={{fontSize:12,color:TEAL}}>Extracting...</span>}
                      {item.status==="pending"&&<span style={{fontSize:12,color:"#aaa"}}>Queued</span>}
                      {item.status==="done"&&<span style={{fontSize:12,color:"#2E7D32",fontWeight:500}}>Ready</span>}
                      {item.status==="error"&&<span style={{fontSize:12,color:"#C62828"}}>Failed</span>}
                    </td>
                    <td style={{padding:"6px 8px"}}><button onClick={function(){removeItem(item.id);}} style={Object.assign({},SS.btnGs,{padding:"3px 8px",fontSize:12,color:"#C62828",borderColor:"#EF9A9A"})}>✕</button></td>
                  </tr>
                );})}
              </tbody>
            </table>
          </div>
          {allDone&&<div style={{display:"flex",alignItems:"center",gap:12}}>
            <button style={SS.btnT} onClick={function(){onSubmit(done);}}>{"Submit "+done.length+" invoice"+(done.length!==1?"s":"")}</button>
            <span style={{fontSize:13,color:"#888"}}>Review fields above before submitting</span>
          </div>}
        </div>
      )}
    </div>
  );
}

export default function App() {
  var [loggedIn,setLoggedIn]=useState(false);
  var [role,setRole]=useState(null);
  var [userName,setUserName]=useState("");
  var [page,setPage]=useState("invoices");
  var [view,setView]=useState("tracker");
  var [bulk,setBulk]=useState(false);
  var [invoices,setInv]=useState([]);
  var [budgets,setBudgets]=useState([]);
  var [selB,setSelB]=useState(null);
  var [form,setForm]=useState(emptyForm);
  var [err,setErr]=useState({});
  var [submitted,setSub]=useState(false);
  var [fStatus,setFS]=useState("All");
  var [search,setSearch]=useState("");
  var [extracting,setExtr]=useState(false);
  var [lang,setLang]=useState(null);
  var [notifs,setNotifs]=useState([]);
  var [showN,setShowN]=useState(false);
  var [loading,setLoading]=useState(false);
  var nRef=useRef();
  var nId=useRef(100);

  useEffect(function(){
    var h=function(e){if(nRef.current&&!nRef.current.contains(e.target))setShowN(false);};
    document.addEventListener("mousedown",h);
    return function(){document.removeEventListener("mousedown",h);};
  },[]);

  useEffect(function(){
    if(loggedIn){loadData();}
  },[loggedIn]);

  async function loadData(){
    setLoading(true);
    var bRes=await supabase.from("budgets").select("*").order("created_at",{ascending:true});
    var iRes=await supabase.from("invoices").select("*").order("created_at",{ascending:false});
    if(bRes.data)setBudgets(bRes.data);
    if(iRes.data)setInv(iRes.data);
    setLoading(false);
  }

  function handleLogin(r,name){setRole(r);setUserName(name);setLoggedIn(true);setView(r==="CE"?"tracker":"approvals");}
  function handleLogout(){setLoggedIn(false);setRole(null);setUserName("");setPage("invoices");setView("tracker");setBulk(false);setSelB(null);}

  var myN=notifs.filter(function(n){return n.role===role;});
  var unread=myN.filter(function(n){return !n.read;}).length;
  function push(r,msg){setNotifs(function(p){return p.concat([{id:nId.current++,role:r,msg:msg,read:false}]);});}
  function markR(){setNotifs(function(p){return p.map(function(n){return n.role===role?Object.assign({},n,{read:true}):n;});});}

  async function updateStatus(id,status){
    await supabase.from("invoices").update({status:status}).eq("id",id);
    await supabase.from("audit_log").insert([{invoice_id:id,action:status,performed_by:userName}]);
    setInv(function(p){return p.map(function(i){return i.id===id?Object.assign({},i,{status:status}):i;});});
    var inv=invoices.find(function(i){return i.id===id;});
    if(inv)push("CE","Invoice "+(inv.invoice_no||inv.invoiceNo)+" has been "+status.toLowerCase());
  }

  async function handleFile(f){
    setExtr(true);setLang(null);
    try{
      var d=await extractInvoiceData(f);
      var autoDue="";
      if(d.invoiceDate){var dt=new Date(d.invoiceDate);dt.setDate(dt.getDate()+30);autoDue=d.dueDate||dt.toISOString().split("T")[0];}
      setForm(function(p){return Object.assign({},p,{fileName:f.name,supplier:d.supplier||p.supplier,invoiceNo:d.invoiceNo||p.invoiceNo,invoiceDate:d.invoiceDate||p.invoiceDate,dueDate:autoDue||p.dueDate,amount:d.amount||p.amount,currency:d.currency&&CURRENCIES.includes(d.currency)?d.currency:p.currency,notes:d.notes||p.notes});});
      if(d.language)setLang(d.language);
    }catch(e){setForm(function(p){return Object.assign({},p,{fileName:f.name});});}
    setExtr(false);
  }

  function validate(){var e={};if(!form.supplier.trim())e.supplier=true;if(!form.invoiceNo.trim())e.invoiceNo=true;if(!form.invoiceDate)e.invoiceDate=true;if(!form.dueDate)e.dueDate=true;if(!form.amount||isNaN(form.amount)||parseFloat(form.amount)<=0)e.amount=true;return e;}

  async function submitInvoice(){
    var e=validate();setErr(e);if(Object.keys(e).length)return;
    var insert={supplier:form.supplier,invoice_no:form.invoiceNo,invoice_date:form.invoiceDate,due_date:form.dueDate,amount:parseFloat(form.amount),currency:form.currency,department:form.department,equipment:form.equipment||null,job_ref:form.jobRef||null,notes:form.notes||null,file_name:form.fileName||null,budget_id:form.budgetId||null,status:"Pending",created_by:userName};
    var res=await supabase.from("invoices").insert([insert]).select();
    if(res.data&&res.data[0]){
      setInv(function(p){return [res.data[0]].concat(p);});
      push("Captain","New invoice from "+form.supplier+" awaiting approval");
      setSub(true);
    }
  }

  function resetForm(){setForm(emptyForm);setErr({});setSub(false);setLang(null);}

  async function submitBulk(done){
    var inserts=done.map(function(x){return {supplier:x.data.supplier,invoice_no:x.data.invoiceNo,invoice_date:x.data.invoiceDate||null,due_date:x.data.dueDate||null,amount:parseFloat(x.data.amount)||0,currency:x.data.currency,department:x.data.department,equipment:x.data.equipment||null,job_ref:x.data.jobRef||null,notes:x.data.notes||null,file_name:x.data.fileName||null,budget_id:x.data.budgetId||null,status:"Pending",created_by:userName};});
    var res=await supabase.from("invoices").insert(inserts).select();
    if(res.data){setInv(function(p){return res.data.concat(p);});}
    push("Captain",done.length+" new invoice"+(done.length!==1?"s":"")+" awaiting approval");
    setBulk(false);setView("tracker");
  }

  var filtered=invoices.filter(function(i){
    var ms=fStatus==="All"||i.status===fStatus;
    var q=search.toLowerCase();
    return ms&&(!q||i.supplier.toLowerCase().includes(q)||(i.invoice_no||"").toLowerCase().includes(q)||(i.job_ref||"").toLowerCase().includes(q));
  });
  var pending=invoices.filter(function(i){return i.status==="Pending";});
  var lF={English:"🇬🇧",Italian:"🇮🇹",French:"🇫🇷"};

  function F(field,label,type,ph,req){
    type=type||"text";ph=ph||"";req=req||false;
    return(<div><Lbl required={req}>{label}</Lbl><input type={type} value={form[field]} placeholder={ph} onChange={function(e){var v=e.target.value;setForm(function(p){return Object.assign({},p,{[field]:v});});}} style={Object.assign({},SS.inp,{borderColor:err[field]?"#C62828":"#ccc"})}/>{err[field]&&<p style={{fontSize:12,color:"#C62828",margin:"4px 0 0"}}>Required</p>}</div>);
  }

  if(!loggedIn)return <LoginScreen onLogin={handleLogin}/>;

  if(loading)return <div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:"#f4f6f8"}}><div style={{textAlign:"center"}}><p style={{fontSize:24,margin:"0 0 8px"}}>⏳</p><p style={{fontSize:14,color:"#888"}}>Loading...</p></div></div>;

  return (
    <div style={{fontFamily:"'Inter','Segoe UI',Arial,sans-serif",background:"#f4f6f8",minHeight:"100vh"}}>
      <div style={{background:"#fff",borderBottom:"1px solid #dde1e7",padding:"0 24px",display:"flex",alignItems:"center",justifyContent:"space-between",height:54}}>
        <span style={{fontSize:18,fontWeight:700,color:TEAL}}>INVOICE PLATFORM</span>
        <div style={{display:"flex",alignItems:"center",gap:12}}>
          <span style={{fontSize:13,color:"#666"}}>{role==="CE"?"🔧":"⚓"} {userName}</span>
          <div style={{position:"relative"}} ref={nRef}>
            <button onClick={function(){setShowN(function(v){return !v;});if(!showN)markR();}} style={Object.assign({},SS.btnGs,{position:"relative"})}>
              🔔{unread>0&&<span style={{position:"absolute",top:-4,right:-4,width:16,height:16,borderRadius:"50%",background:"#F44336",color:"#fff",fontSize:10,fontWeight:700,display:"flex",alignItems:"center",justifyContent:"center"}}>{unread}</span>}
            </button>
            {showN&&<div style={{position:"absolute",right:0,top:"calc(100% + 6px)",width:300,background:"#fff",border:"1px solid #dde1e7",borderRadius:6,zIndex:300,boxShadow:"0 6px 20px rgba(0,0,0,.1)",overflow:"hidden"}}>
              <p style={{padding:"12px 16px",fontSize:14,fontWeight:600,margin:0,borderBottom:"1px solid #f0f0f0"}}>Notifications</p>
              {myN.length===0&&<p style={{padding:"1rem 16px",fontSize:13,color:"#888",margin:0}}>Nothing yet</p>}
              {myN.slice().reverse().map(function(n){return <div key={n.id} style={{padding:"11px 16px",borderBottom:"1px solid #f5f5f5",background:n.read?"#fff":"#f0fbfc",fontSize:13,color:"#333",lineHeight:1.5}}>{n.msg}</div>;})}
            </div>}
          </div>
          <button onClick={handleLogout} style={Object.assign({},SS.btnGs,{fontSize:13})}>🚪 Sign out</button>
        </div>
      </div>

      <div style={{background:NAV_BG,padding:"0 24px",display:"flex"}}>
        {[{key:"invoices",label:"🧾 Invoices"},{key:"budgets",label:"📊 Budgets"}].map(function(n){return(
          <button key={n.key} onClick={function(){setPage(n.key);setSelB(null);setBulk(false);}}
            style={{padding:"13px 20px",fontSize:13,fontWeight:page===n.key?600:400,color:page===n.key?"#fff":"rgba(255,255,255,0.65)",background:page===n.key?TEAL:"transparent",border:"none",cursor:"pointer",borderBottom:page===n.key?"3px solid #fff":"3px solid transparent",whiteSpace:"nowrap"}}>
            {n.label}
          </button>
        );})}
      </div>

      {page==="invoices"&&!bulk&&<div style={{background:"#fff",borderBottom:"1px solid #dde1e7",padding:"0 24px",display:"flex"}}>
        {(role==="CE"?["tracker","upload"]:["approvals"]).map(function(v){return(
          <button key={v} onClick={function(){setView(v);}}
            style={{padding:"12px 18px",fontSize:14,fontWeight:view===v?600:400,color:view===v?TEAL:"#555",background:"transparent",border:"none",borderBottom:view===v?"3px solid "+TEAL:"3px solid transparent",cursor:"pointer",display:"flex",alignItems:"center",gap:7,marginBottom:-1}}>
            {v==="tracker"?"📋 Tracker":v==="upload"?"⬆️ Upload":"✅ Approvals"}
            {v==="approvals"&&pending.length>0&&<span style={{background:"#FF9800",color:"#fff",fontSize:11,fontWeight:700,padding:"1px 7px",borderRadius:10}}>{pending.length}</span>}
          </button>
        );})}
      </div>}

      <div style={{padding:24}}>
        {page==="budgets"&&!selB&&<BudgetList budgets={budgets} invoices={invoices} onSelect={setSelB} onAdd={function(b){setBudgets(function(p){return p.concat([b]);});}}/>}
        {page==="budgets"&&selB&&<BudgetDetail budget={budgets.find(function(b){return b.id===selB;})} invoices={invoices} budgets={budgets} onBack={function(){setSelB(null);}} onStatus={updateStatus}/>}
        {page==="invoices"&&bulk&&<BulkUpload onBack={function(){setBulk(false);}} onSubmit={submitBulk} budgets={budgets}/>}

        {page==="invoices"&&!bulk&&view==="tracker"&&<div>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}>
            <div><p style={{fontSize:20,fontWeight:700,color:"#222",margin:"0 0 2px"}}>Invoice tracker</p><p style={{fontSize:13,color:"#888",margin:0}}>{role==="CE"?"Chief engineer":"Captain"}</p></div>
            {role==="CE"&&<div style={{display:"flex",gap:8}}>
              <button style={SS.btnT} onClick={function(){setView("upload");}}>+ New invoice</button>
              <button style={SS.btnO} onClick={function(){setBulk(true);}}>📂 Bulk upload</button>
            </div>}
          </div>
          <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:16,marginBottom:20}}>
            {["Pending","Approved","Rejected"].map(function(s,i){
              var total=invoices.filter(function(x){return x.status===s;}).reduce(function(t,x){return t+parseFloat(x.amount||0);},0);
              return <StatCard key={s} label={s} value={invoices.filter(function(x){return x.status===s;}).length} sub={"EUR "+fmt(total)} accent={["#FF9800","#4CAF50","#F44336"][i]}/>;
            })}
          </div>
          <div style={SS.card}>
            <div style={{padding:"14px 16px",borderBottom:"1px solid #f0f0f0",display:"flex",gap:10,flexWrap:"wrap",alignItems:"center"}}>
              <input placeholder="🔍 Search supplier, invoice no., job ref…" value={search} onChange={function(e){setSearch(e.target.value);}} style={Object.assign({},SS.inp,{flex:1,minWidth:180})}/>
              <div style={{display:"flex",gap:6}}>{["All","Pending","Approved","Rejected"].map(function(s){return <button key={s} onClick={function(){setFS(s);}} style={fStatus===s?SS.btnTs:SS.btnGs}>{s}</button>;})}</div>
            </div>
            <InvoiceTable invoices={filtered} budgets={budgets} onStatus={updateStatus} showActions={true}/>
            <div style={{padding:"10px 16px",borderTop:"1px solid #f0f0f0"}}><span style={{fontSize:13,color:"#888"}}>{filtered.length+" invoice"+(filtered.length!==1?"s":"")+" shown"}</span></div>
          </div>
        </div>}

        {page==="invoices"&&!bulk&&view==="upload"&&!submitted&&<div>
          <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:20}}>
            <button style={SS.btnGs} onClick={function(){setView("tracker");}}>← Back</button>
            <p style={{fontSize:20,fontWeight:700,color:"#222",margin:0}}>Upload invoice</p>
          </div>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20,maxWidth:860}}>
            <div style={Object.assign({},SS.card,{padding:20})}>
              <p style={{fontSize:15,fontWeight:600,color:"#222",margin:"0 0 14px",paddingBottom:10,borderBottom:"2px solid "+TEAL,display:"inline-block"}}>Attach document</p>
              <DropZone onFile={handleFile} fileName={form.fileName} extracting={extracting}/>
              {lang&&<div style={{marginTop:12,padding:"10px 14px",background:"#E8F5E9",borderRadius:4,border:"1px solid #A5D6A7",fontSize:13,color:"#2E7D32"}}>{"✨ Extracted from "+lang+" "+(lF[lang]||"")+" — review fields"}</div>}
            </div>
            <div style={Object.assign({},SS.card,{padding:20})}>
              <p style={{fontSize:15,fontWeight:600,color:"#222",margin:"0 0 14px",paddingBottom:10,borderBottom:"2px solid "+TEAL,display:"inline-block"}}>Invoice details</p>
              <div style={{display:"flex",flexDirection:"column",gap:14}}>
                <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
                  {F("supplier","Supplier name","text","e.g. Seatech",true)}
                  {F("invoiceNo","Invoice number","text","e.g. INV-001",true)}
                  <div><Lbl required>Invoice date</Lbl><input type="date" value={form.invoiceDate} onChange={function(e){var d=e.target.value;var due="";if(d){var dt=new Date(d);dt.setDate(dt.getDate()+30);due=dt.toISOString().split("T")[0];}setForm(function(p){return Object.assign({},p,{invoiceDate:d,dueDate:due});});}} style={Object.assign({},SS.inp,{borderColor:err.invoiceDate?"#C62828":"#ccc"})}/>{err.invoiceDate&&<p style={{fontSize:12,color:"#C62828",margin:"4px 0 0"}}>Required</p>}</div>
                  <div><Lbl required>Due date <span style={{fontWeight:400,color:"#aaa",fontSize:11}}>auto +30 days</span></Lbl><input type="date" value={form.dueDate} onChange={function(e){var v=e.target.value;setForm(function(p){return Object.assign({},p,{dueDate:v});});}} style={Object.assign({},SS.inp,{borderColor:err.dueDate?"#C62828":"#ccc"})}/>{err.dueDate&&<p style={{fontSize:12,color:"#C62828",margin:"4px 0 0"}}>Required</p>}</div>
                </div>
                <div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:12}}>
                  <div><Lbl required>Amount</Lbl><input type="number" min="0" step="0.01" value={form.amount} placeholder="0.00" onChange={function(e){var v=e.target.value;setForm(function(p){return Object.assign({},p,{amount:v});});}} style={Object.assign({},SS.inp,{borderColor:err.amount?"#C62828":"#ccc"})}/>{err.amount&&<p style={{fontSize:12,color:"#C62828",margin:"4px 0 0"}}>Required</p>}</div>
                  <div><Lbl>Currency</Lbl><select value={form.currency} onChange={function(e){var v=e.target.value;setForm(function(p){return Object.assign({},p,{currency:v});});}} style={SS.inp}>{CURRENCIES.map(function(c){return <option key={c}>{c}</option>;})}</select></div>
                </div>
                <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
                  <div><Lbl>Department</Lbl><select value={form.department} onChange={function(e){var v=e.target.value;setForm(function(p){return Object.assign({},p,{department:v});});}} style={SS.inp}>{DEPARTMENTS.map(function(d){return <option key={d}>{d}</option>;})}</select></div>
                  {F("jobRef","Job reference","text","e.g. JR-001")}
                </div>
                <div><Lbl>Equipment</Lbl><select value={form.equipment} onChange={function(e){var v=e.target.value;setForm(function(p){return Object.assign({},p,{equipment:v});});}} style={SS.inp}><option value="">— None —</option>{EQUIPMENT.filter(function(e){return e;}).map(function(eq){return <option key={eq}>{eq}</option>;})}</select></div>
                <div><Lbl>Assign to budget</Lbl><select value={form.budgetId} onChange={function(e){var v=e.target.value;setForm(function(p){return Object.assign({},p,{budgetId:v||""});});}} style={SS.inp}><option value="">— None —</option>{budgets.map(function(b){return <option key={b.id} value={b.id}>{b.name}</option>;})}</select></div>
                <div><Lbl>Notes</Lbl><textarea value={form.notes} rows={2} placeholder="Additional details…" onChange={function(e){var v=e.target.value;setForm(function(p){return Object.assign({},p,{notes:v});});}} style={Object.assign({},SS.inp,{resize:"vertical",lineHeight:1.5})}/></div>
                <div style={{display:"flex",gap:10}}><button style={SS.btnT} onClick={submitInvoice} disabled={extracting}>Submit invoice</button><button style={SS.btnG} onClick={resetForm}>Clear</button></div>
              </div>
            </div>
          </div>
        </div>}

        {page==="invoices"&&!bulk&&view==="upload"&&submitted&&<div style={{maxWidth:440,margin:"3rem auto",textAlign:"center"}}>
          <div style={{width:60,height:60,borderRadius:"50%",background:"#E8F5E9",display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 16px",fontSize:28}}>✓</div>
          <p style={{fontSize:18,fontWeight:700,color:"#222",marginBottom:8}}>Invoice submitted</p>
          <p style={{fontSize:14,color:"#666",marginBottom:24,lineHeight:1.6}}>{(form.invoiceNo||"Invoice")+" from "}<strong>{form.supplier}</strong>{" is pending. Captain notified."}</p>
          <div style={{display:"flex",gap:10,justifyContent:"center"}}>
            <button style={SS.btnT} onClick={resetForm}>Submit another</button>
            <button style={SS.btnO} onClick={function(){setView("tracker");setSub(false);}}>View tracker</button>
          </div>
        </div>}

        {page==="invoices"&&!bulk&&view==="approvals"&&<div>
          <div style={{marginBottom:20}}><p style={{fontSize:20,fontWeight:700,color:"#222",margin:"0 0 2px"}}>Approvals</p><p style={{fontSize:13,color:"#888",margin:0}}>Captain</p></div>
          <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:16,marginBottom:24}}>
            <StatCard label="Awaiting" value={pending.length} accent="#FF9800"/>
            <StatCard label="Approved" value={invoices.filter(function(i){return i.status==="Approved";}).length} accent="#4CAF50"/>
            <StatCard label="Rejected" value={invoices.filter(function(i){return i.status==="Rejected";}).length} accent="#F44336"/>
          </div>
          {pending.length===0&&<div style={Object.assign({},SS.card,{padding:"3rem",textAlign:"center"})}><p style={{fontSize:32,margin:"0 0 12px"}}>✅</p><p style={{fontSize:16,fontWeight:600,color:"#333",margin:"0 0 4px"}}>All caught up</p><p style={{fontSize:14,color:"#999",margin:0}}>No invoices pending</p></div>}
          {pending.map(function(inv){
            var budget=budgets.find(function(b){return b.id===(inv.budget_id||inv.budgetId);});
            return(
              <div key={inv.id} style={Object.assign({},SS.card,{marginBottom:12,borderLeft:"4px solid "+TEAL})}>
                <div style={{padding:"16px 20px"}}>
                  <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:16}}>
                    <div>
                      <p style={{fontSize:16,fontWeight:600,color:"#222",margin:"0 0 4px"}}>{inv.supplier}</p>
                      <p style={{fontSize:13,color:"#777",margin:0}}>{(inv.invoice_no||inv.invoiceNo)+" · "+inv.department+(inv.equipment?" · "+inv.equipment:"")+" · "+(inv.invoice_date||inv.invoiceDate)+(inv.job_ref||inv.jobRef?" · Ref: "+(inv.job_ref||inv.jobRef):"")}</p>
                    </div>
                    <div style={{textAlign:"right",flexShrink:0}}>
                      <p style={{fontSize:20,fontWeight:700,color:"#222",margin:"0 0 3px"}}>{inv.currency+" "+fmt(inv.amount)}</p>
                      {budget&&<p style={{fontSize:12,color:"#888",margin:0}}>{budget.name}</p>}
                    </div>
                  </div>
                  {inv.notes&&<p style={{fontSize:13,color:"#555",padding:"9px 12px",background:"#f7f8fa",borderRadius:4,borderLeft:"3px solid #dde1e7",margin:"12px 0 0"}}>{inv.notes}</p>}
                  <div style={{display:"flex",gap:8,marginTop:14}}>
                    <button style={SS.btnTs} onClick={function(){updateStatus(inv.id,"Approved");}}>✓ Approve</button>
                    <button style={Object.assign({},SS.btnGs,{color:"#C62828",borderColor:"#EF9A9A"})} onClick={function(){updateStatus(inv.id,"Rejected");}}>✕ Reject</button>
                  </div>
                </div>
              </div>
            );
          })}
          {invoices.filter(function(i){return i.status==="Approved";}).length>0&&<div>
            <p style={{fontSize:13,fontWeight:600,color:"#888",textTransform:"uppercase",letterSpacing:"0.05em",margin:"24px 0 10px"}}>Approved — ready for Sage</p>
            <div style={SS.card}><InvoiceTable invoices={invoices.filter(function(i){return i.status==="Approved";})} budgets={budgets} onStatus={updateStatus} showActions={false}/></div>
          </div>}
          {invoices.filter(function(i){return i.status==="Rejected";}).length>0&&<div>
            <p style={{fontSize:13,fontWeight:600,color:"#888",textTransform:"uppercase",letterSpacing:"0.05em",margin:"20px 0 10px"}}>Rejected</p>
            <div style={SS.card}><InvoiceTable invoices={invoices.filter(function(i){return i.status==="Rejected";})} budgets={budgets} onStatus={updateStatus} showActions={true}/></div>
          </div>}
        </div>}
      </div>
    </div>
  );
}
